eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8080/eureka/
server:
  port: 8090
spring:
  application:
    name: server-feign
  thymeleaf:
    cache: false
    prefix: classpath:/templates/
    suffix: .html
  main:
    allow-bean-definition-overriding: true