eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8080/eureka/
server:
  port: 8081
spring:
  application:
    name: feign-server
  main:
    allow-bean-definition-overriding: true
  feign:
    hystrix:
      enabled: true
