server:
  port: 8083

spring:
  application:
    name: server-zsg
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/1902?useUnicode=true&characterEncoding=utf-8
    #url: jdbc:mysql://192.168.2.111:3307/1902?useUnicode=true&characterEncoding=utf-8
    #username: root
    #password:
    data-username: root
    data-password: 0604


eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8080/eureka/
  instance:
    lease-renewal-interval-in-seconds: 1
    lease-expiration-duration-in-seconds: 2

mybatis:
  config-locations: classpath:mapping/config.xml
  mapper-locations: classpath:mapping/mapper/*.xml
  type-aliases-package: com.jk.model

