eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8080/eureka/
server:
  port: 8095
spring:
  application:
    name: feign-dangdang
  redis:
    host: localhost
    jedis:
      pool:
        max-active: 8
        max-idle: 8
        max-wait: -1
        min-idle: 0
    port: 6379
    timeout: 10000

  data:
    mongodb:
      database: haha
      host: localhost
<<<<<<< HEAD
      port: 27017
=======
      port: 27017


  main:
    allow-bean-definition-overriding: true
    thymeleaf:
      cache: false
      prefix: classpath:/templates/
      suffix: .html

elasticsearch:
  clusterName: my-application
  ip: 127.0.0.1
  firstPort: 9300
  secondPort: 9301
  thirdPort: 9302
>>>>>>> origin/master
