eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8080/eureka/
server:
  port: 8095
spring:
  application:
    name: feign-dangdang
  thymeleaf:
    cache: false
    prefix: classpath:/templates/
    suffix: .html