eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8080/eureka/
server:
  port: 8091
spring:
  application:
    name: feign-dangdang

  main:
    allow-bean-definition-overriding: true
    thymeleaf:
      cache: false
      prefix: classpath:/templates/
      suffix: .html

elasticsearch:
  clusterName: my-application
  ip: 127.0.0.1
  firstPort: 9300
  secondPort: 9301
  thirdPort: 9302