server:
 port: 8085
spring:
  application:
    name: server-ayr
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    password: 123
    url: jdbc:mysql://localhost:3306/ayr801?useUnicode=true&characterEncoding=utf-8
    username: root

    main:
      allow-bean-definition-overriding: true
  data:
    mongodb:
      database: haha
      host: localhost
      port: 27017
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8080/eureka/
mybatis:
  config-locations: classpath:mapping/conf/confg.xml
  mapper-locations: classpath:mapping/*.xml
  type-aliases-package: com.jk.model
